# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "sprockets-urlrewriter/version"

Gem::Specification.new do |s|
  s.name        = "sprockets-urlrewriter"
  s.version     = SprocketsUrlRewriter::VERSION
  s.authors     = ["Carl Hoerberg"]
  s.email       = ["carl.hoerberg@gmail.com"]
  s.homepage    = "http://github.com/carlhoerberg/sprockets-urlrewriter"
  s.summary     = %q{Makes absolut urls in CSS files generated by Sprockets}
  s.description = %q{ Replaces all instances of url() in CSS files Sprockets concats, if the url is relative. }

  s.rubyforge_project = "sprockets-urlrewriter"

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]

  s.add_development_dependency "minitest"
  s.add_runtime_dependency "sprockets"
end
